apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-ssh-creds-secret
  namespace: tekton-pipelines
data:
  id_rsa: <top-secret>
  known_hosts: <top-secret>
  config: <top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: nakodeelee-reg-cred
  namespace: tekton-pipelines
data:
  config.json: <top-secret>


