apiVersion: v1
kind: ServiceAccount
metadata:
  name: notalone-pipeline-trigger-sa
  namespace: tekton-pipelines
---

apiVersion: v1
kind: Secret
metadata:
  name: notalone-pipeline-trigger-sa-kube-notalone-secret
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/service-account.name: notalone-pipeline-trigger-sa
type: kubernetes.io/service-account-token
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: notalone-pipeline-trigger-role
  namespace: tekton-pipelines
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"] # secrets are only needed for Github/Gitlab interceptors
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
  # Permisnions to create EL pods
  - apiGroups: ["extensions", "apps", ""]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notalone-pipeline-trigger-role-binding
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notalone-pipeline-trigger-role
subjects:
  - kind: ServiceAccount
    name: notalone-pipeline-trigger-sa
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: notalone-tekton-triggers-eventlistener-clusterroles
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clustertriggerbindings", "clusterinterceptors"]
    verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notalone-pipeline-trigger-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: notalone-pipeline-trigger-sa
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notalone-tekton-triggers-eventlistener-clusterroles
